### ISSUE TITLE
Loading icon for slow connections (when loading the JSON)

### ISSUE THREAD

**Issue by nouveller** [daviddarnes/currentstat.us#15]
@daviddarnes This would be a good place for that animated SVG. We not currently utilising it are we?

**Comment by daviddarnes** [comment]
No we are not, this is perfect for it. CodePen link http://codepen.io/daviddarnes/pen/gPMdVe

**Comment by daviddarnes** [comment]
Note: To stop the animations all firing at the same time we should add some CSS for an `animation-delay`, so it creates a colour waterfall effect.

**Comment by nouveller** [comment]
No need for this as the JSON is gonna be inline. :tada:
