### ISSUE TITLE
The "fold"

### ISSUE THREAD

**Issue by nouveller** [daviddarnes/currentstat.us#27]
Heheh, the issue title made me laugh.

As the images are so perfectly sized, it looks like you can't scroll to discover any more gifs. So, one option is to set the height of the `.status` to `height: calc(33.33vh - 10px);`.

This results in the following, thoughts?

![screen shot 2016-01-19 at 19 47 34](https://cloud.githubusercontent.com/assets/713128/12430096/a01b327c-bee5-11e5-8748-c3e05a87b356.png)

**Comment by daviddarnes** [comment]
Eh, I'm not bothered. I instantly scroll any site so I don't really see the issue. Plus focus is on the text input, so it kinda doesn't matter about scrolling.

**Comment by nouveller** [comment]
Heh, I did think it seemed a bit silly. It just thought when you'd approved those extra gifs where they were gonna go. Closing
