### ISSUE TITLE
Logo / Icon / Favicon Idea

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/currentstat.us#6]
I couldn't embed it on here, but here's the link instead http://codepen.io/daviddarnes/pen/gPMdVe/

@nouveller thoughts?

**Comment by nouveller** [comment]
Ha, love it!

**Comment by daviddarnes** [comment]
@nouveller Couldn't animate it for the favicons :panda_face:. Will stick with the bright green for now.
